### ISSUE TITLE
Consider dbus-introspection instead?

### ISSUE THREAD

**Issue by superm1** [pop-os/fwupd-dbus#1]
I'm a bit curious - why did you choose to write a wrapper for the dbus interface, when you could have instead used gobject introspection (for example https://github.com/gtk-rs/gir)?  I think the later would be easier to maintain rather than watching the changes in API and duplicating in this layer.

**Comment by mmstick** [comment]
If you know how to do it, feel free to submit a PR. If it can generate an ergonomic API, that would be nice.

**Comment by mmstick** [comment]
I don't think gir is applicable here because we are not using GObject in Rust, nor is this a binding to a GObject library.

**Comment by mmstick** [comment]
The [dbus-codegen crate] could work, generating DBus bindings from DBus introspection. However, there's a lot of information missing from the introspection data, and the generated bindings are not ergonomic to interface with, so they would still require to be wrapped in a proper API.

[dbus-codegen crate]: https://github.com/diwic/dbus-rs/tree/master/dbus-codegen

**Comment by superm1** [comment]
But the FwupdClient and FwupdDevice objects make implementing a frontend a lot more straightforward rather than implementation of an API that a frontend would use.

As an example of what an introspection built client looks like in another language (python); https://github.com/hughsie/fwupd/blob/master/contrib/simple_client.py

**Comment by mmstick** [comment]
We don't plan to create bindings to a C library, which binds to a DBus API, when we can simply bind to the DBus API and avoid the unsafe dependency in the middle. It's not much effort for us to maintain a native Rust client, so I don't think we need it.
